#!/usr/bin/env ruby
# chmod 744 Tools/scripts/subtree

# Tools/scripts/subtree add apps
# Tools/scripts/subtree add tools

# Tools/scripts/subtree push apps
# Tools/scripts/subtree push tools

action = ARGV.first.strip.downcase
list   = ARGV.last.strip.downcase + '.rb'

require_relative "subtree_lists/#{list}"

subtrees_dir = ''
subtrees = SUBTREES.each_slice(3)

if action == 'add'
  subtrees.each do |item|
    local_path  = item[0]
    remote_repo = item[1]
    branch      = item[2]

    puts cmd = "
      git subtree add \
        --prefix #{subtrees_dir}#{local_path} \
        #{remote_repo} \
        #{branch} --squash
    "

    system cmd
  end
elsif action == 'push'
  subtrees.each do |item|
    local_path  = item[0]
    remote_repo = item[1]
    branch      = item[2]

    puts cmd = "
      git subtree push \
        --prefix #{subtrees_dir}#{local_path} \
        #{remote_repo} \
        #{branch}
    "
    system cmd
  end
elsif action == 'pull'
  subtrees.each do |item|
    local_path  = item[0]
    remote_repo = item[1]
    branch      = item[2]

    puts cmd = "
      git subtree pull \
        --prefix #{subtrees_dir}#{local_path} \
        #{remote_repo} \
        #{branch}
    "

    system cmd
  end
else
  puts 'Undefined action. Acceptable values: [ add | push | pull ]'
end
