#!/usr/bin/env ruby
# chmod 744 Tools/scripts/subtree

# Tools/scripts/subtree add apps
# Tools/scripts/subtree add tools

# Tools/scripts/subtree push apps
# Tools/scripts/subtree push tools

action = ARGV.first.strip.downcase
list   = ARGV.last.strip.downcase + '.rb'

require 'colorize'
require_relative "subtree_lists/#{list}"

def execute_cmd cmd
  puts cmd.strip.red
  system cmd
end

subtrees_dir = ''
subtrees = SUBTREES.each_slice(3)

if action == 'add'
  subtrees.each do |item|
    local_path  = item[0]
    remote_repo = item[1]
    branch      = item[2]

    execute_cmd "
      git subtree add --prefix #{subtrees_dir}#{local_path} #{remote_repo} #{branch} --squash
    "
  end
elsif action == 'push'
  subtrees.each do |item|
    local_path  = item[0]
    remote_repo = item[1]
    branch      = item[2]

    execute_cmd "
      git subtree push --prefix #{subtrees_dir}#{local_path} #{remote_repo} #{branch}
    "
  end
elsif action == 'pull'
  subtrees.each do |item|
    local_path  = item[0]
    remote_repo = item[1]
    branch      = item[2]

    execute_cmd "
      git subtree pull --prefix #{subtrees_dir}#{local_path} #{remote_repo} #{branch}
    "
  end
elsif action == 'push-force'
  subtrees.each do |item|
    local_path  = item[0]
    remote_repo = item[1]
    branch      = item[2]

    execute_cmd "
      git push #{remote_repo} \`git subtree split --prefix #{subtrees_dir}#{local_path} master\`:#{branch} --force
    "
  end
else
  puts 'Undefined action. Acceptable values: [ add | push | pull ]'
end
