gem 'to_slug_param',      path: '../Engines/tools/to_slug_param'
gem 'the_string_addon',   path: '../Engines/tools/the_string_addon'
gem 'friendly_id_pack',   path: '../Engines/tools/friendly_id_pack'
gem 'the_notifications',  path: '../Engines/tools/notifications'
gem 'the_pagination',     path: '../Engines/tools/pagination'
gem 'active_permits',     path: '../Engines/tools/authorize_it'
gem 'simple_sort',        path: '../Engines/tools/simple_sort'
gem 'image_tools',        path: '../Engines/tools/image_tools'
gem 'voiceless',          path: '../Engines/tools/voiceless'
gem 'crop_tool',          path: '../Engines/tools/crop_tool'
gem 'protozaur',          path: '../Engines/tools/protozaur'
gem 'log_js',             path: '../Engines/tools/log_js'

gem 'user_room',         path: '../Engines/apps/user_room'
gem 'the_publication',   path: '../Engines/apps/the_publication'
gem 'app_base',          path: '../Engines/apps/app_base'
gem 'app_theme',         path: '../Engines/apps/theopencms.org'
