gem 'friendly_id_pack',  path: '../../Engines/TheOpenCMS/friendly_id_pack'
gem 'the_notifications', path: '../../Engines/TheOpenCMS/notifications'
gem 'the_pagination',    path: '../../Engines/TheOpenCMS/pagination'
gem 'simple_sort',       path: '../../Engines/TheOpenCMS/simple_sort'
gem 'image_tools',       path: '../../Engines/TheOpenCMS/image_tools'
gem 'voiceless',         path: '../../Engines/TheOpenCMS/voiceless'
gem 'crop_tool',         path: '../../Engines/TheOpenCMS/crop_tool'
gem 'protozaur',         path: '../../Engines/Protozaur/protozaur'
gem 'log_js',            path: '../../Engines/TheOpenCMS/log_js'

gem 'authorize_it',      path: '../../Engines/TheOpenCMS/authorize_it'
gem 'user_room',         path: '../../Engines/TheOpenCMS/user_room'
gem 'the_publication',   path: '../../Engines/TheOpenCMS/the_publication'

gem 'app_base',          path: '../../Engines/TheOpenCMS/app_base'
gem 'app_theme',         path: '../../Engines/Addons/theopencms.org'
