gem 'voiceless',         path: '../../SUBTREES/TheOpenCMS/voiceless'
gem 'user_room',         path: '../../SUBTREES/TheOpenCMS/user_room'
gem 'the_pagination',    path: '../../SUBTREES/TheOpenCMS/pagination'
gem 'the_notifications', path: '../../SUBTREES/TheOpenCMS/notifications'
gem 'simple_sort',       path: '../../SUBTREES/TheOpenCMS/simple_sort'
gem 'image_tools',       path: '../../SUBTREES/TheOpenCMS/image_tools'
gem 'crop_tool',         path: '../../SUBTREES/TheOpenCMS/crop_tool'
gem 'log_js',            path: '../../SUBTREES/TheOpenCMS/log_js'
