gem 'voiceless',         path: '../../Engines/TheOpenCMS/voiceless'
gem 'the_notifications', path: '../../Engines/TheOpenCMS/notifications'
gem 'the_pagination',    path: '../../Engines/TheOpenCMS/pagination'
gem 'simple_sort',       path: '../../Engines/TheOpenCMS/simple_sort'
gem 'image_tools',       path: '../../Engines/TheOpenCMS/image_tools'
gem 'crop_tool',         path: '../../Engines/TheOpenCMS/crop_tool'
gem 'log_js',            path: '../../Engines/TheOpenCMS/log_js'

gem 'user_room',         path: '../../Engines/TheOpenCMS/user_room'
gem 'app_base',          path: '../../Engines/TheOpenCMS/app_base'
