# THIS FILE WAS GENERATED BY DEPLOY TOOL

# https://github.com/puma/puma/blob/master/examples/config.rb
# https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-puma-and-nginx-on-ubuntu-14-04

workers 2
threads 5, 10
daemonize true
environment "<%= kit.app_env %>"

bind "unix://<%= kit.shared_sockets_path %>/puma.sock"

pidfile    "<%= kit.shared_pids_path %>/puma.pid"
state_path "<%= kit.shared_pids_path %>/puma.state"

stdout_redirect \
  "<%= kit.shared_logs_path %>/puma.log",
  "<%= kit.shared_logs_path %>/puma.errors.log",
  true

activate_control_app

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load_file("<%= kit.copy_db_config_path %>")["<%= kit.app_env %>"])
end

