db:
  host: localhost
  pool: 5

  username: rails
  database: rails_app_db
  password: SECRETPASSWORD

  adapter: postgresql
  encoding: unicode
  port: 5432

  # adapter: mysql
  # encoding: utf8
  # port: 3306
  # socket: /tmp/socket.sock
